language: R
cache: packages
sudo: false
warnings_are_errors: true

matrix:
  include:
    - os: linux
      r : release
    - os: linux
      r : devel
    - os: osx
      brew_packages: apache-arrow llvm
      r : release

r_packages:
  - covr
  - testthat
  - lintr
  - data.table
  - arrow
  - fst
  - crayon
  - microbenchmark
  - progress

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CPPFLAGS="-I/usr/local/opt/llvm/include"; fi

after_success:
  - Rscript -e 'library(covr); codecov(quiet = FALSE)'

env:
  global:
    - PKG_CFLAGS="-Wall -pedantic"

# copied from https://github.com/jeroen/arrow-r-dev
addons:
  apt:
    update: true
    sources:
      - sourceline: 'deb [arch=amd64] http://dl.bintray.com/apache/arrow/ubuntu xenial main'
        key_url: 'https://dist.apache.org/repos/dist/dev/arrow/KEYS'
    packages: 'libarrow-dev libparquet-dev'