# DO NOT CHANGE the "init" and "install" sections below

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps:   Bootstrap


environment:
  global:
    CRAN: http://cloud.r-project.org/
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true
    GCC_PATH: mingw_64
# Default GCC_PATH appears to be gcc-4.6.3 which is now unsupported as from Rtools.exe v3.4
    R_CHECK_ARGS: --no-manual
# R_CHECK_ARGS specified in order to turn off --as-cran as that can be slow

  matrix:
  - R_VERSION: release
    R_ARCH: x64

  - R_VERSION: devel
    R_ARCH: x64


build_script:
  - set _R_CHECK_FORCE_SUGGESTS_=false
  - travis-tool.sh r_install Rcpp
  - travis-tool.sh r_install testthat
  - travis-tool.sh r_install lintr

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
