// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cubic_spline
void cubic_spline(SEXP double_values, SEXP estimates);
RcppExport SEXP _synthetic_cubic_spline(SEXP double_valuesSEXP, SEXP estimatesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type double_values(double_valuesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type estimates(estimatesSEXP);
    cubic_spline(double_values, estimates);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_synthetic_cubic_spline", (DL_FUNC) &_synthetic_cubic_spline, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_synthetic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
