# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rspline <- function(control_values, nr_of_draws, seed_dbl) {
    .Call(`_synthetic_rspline`, control_values, nr_of_draws, seed_dbl)
}

