# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_spline <- function(control_values, nr_of_draws, seed_dbl, x_overflow) {
    .Call(`_synthetic_random_spline`, control_values, nr_of_draws, seed_dbl, x_overflow)
}

simulate_spline <- function(control_points, x_points) {
    .Call(`_synthetic_simulate_spline`, control_points, x_points)
}

